### PR TITLE
Update version on cabal file

### PR DESCRIPTION
**Pull request by themattchan**
Also, the `v0.1.0.0` release is missing a cabal file and this is causing issues with my project. I don't know if tags can be updated but I hope that the cabal file could be backported to that release.

### CODE REVIEW

**Comment by newhoggy** [comment]
How can I reproduce the issue you are having?

**Comment by themattchan** [comment]
The other issue turned out to be caused by an old version of `cabal2nix` and some bad nix settings, not with the `v0.1.0.0` release.

**Comment by newhoggy** [comment]
The reason the cabal file was missing was that it was meant to be generated by `hpack`.  The project has since been modified to no longer use `hpack`.  The cabal file on `master` is substantially different what `hpack` would have generated.  Does it help you if I release `0.1.0.1`?

**Comment by newhoggy** [comment]
I've released `0.1.0.1` and also move the `v0.1.0.0` tag to a commit that has the correct cabal file.  Hope that helps!

**Comment by themattchan** [comment]
Thanks @newhoggy!

**Pull request merged**
